# Generated by Django 2.1.3 on 2018-12-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100, verbose_name='school name')),
                ('school_site', models.URLField(verbose_name='school website')),
                ('start_dt', models.DateField(verbose_name='start date')),
                ('end_dt', models.DateField(verbose_name='end date')),
                ('degree', models.CharField(help_text='Bachelor, Master, Doctor', max_length=20)),
                ('major', models.CharField(max_length=100, verbose_name='school major')),
                ('course', models.TextField(verbose_name='major course')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='company name')),
                ('company_site', models.URLField(verbose_name='company site')),
                ('start_dt', models.DateField(verbose_name='start date')),
                ('end_dt', models.DateField(verbose_name='end date')),
                ('title', models.CharField(max_length=50)),
                ('product', models.TextField(help_text='leading or attend projects, markdown')),
                ('duties', models.CharField(max_length=100)),
                ('tech_stack', models.TextField(help_text='technology stack, markdown')),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
            },
        ),
    ]
