# Generated by Django 2.1.3 on 2018-11-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_img',
            field=models.CharField(blank=True, help_text='your article cover image', max_length=1000, verbose_name='cover image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_copyright',
            field=models.CharField(blank=True, help_text='image copyright notice', max_length=100, verbose_name='copyright'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_dt',
            field=models.DateTimeField(db_index=True, verbose_name='publish date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(help_text='suggest: lower-case|-|0-9', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_dt',
            field=models.DateTimeField(db_index=True, verbose_name='update date'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(help_text='suggest: lower-case|-|0-9', max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
