# Generated by Django 2.1.3 on 2018-12-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181122_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='avatar',
            field=models.URLField(default='https://www.gravatar.com/avatar/00000000000000000000000000000000'),
        ),
    ]
