# Generated by Django 2.1.7 on 2019-03-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pv',
            field=models.IntegerField(default=0, verbose_name='page views'),
        ),
    ]
