# Generated by Django 2.2.3 on 2019-07-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('desc', models.TextField(blank=True, help_text='support markdown', verbose_name='desc')),
                ('code', models.TextField(help_text='pure code', verbose_name='code')),
                ('pl_tag', models.CharField(db_index=True, help_text='https://github.com/conorhastings/react-syntax-highlighter/blob/master/AVAILABLE_LANGUAGES_PRISM.MD', max_length=20, verbose_name='programming language tag')),
                ('publish_dt', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='publish date')),
                ('update_dt', models.DateTimeField(auto_now=True, db_index=True, verbose_name='update date')),
            ],
            options={
                'verbose_name': 'Snippet',
                'verbose_name_plural': 'Snippets',
                'ordering': ('-publish_dt',),
            },
        ),
    ]
