# Generated by Django 2.1.3 on 2018-11-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MicroBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_img', models.URLField(blank=True)),
                ('content', models.TextField(help_text='text, not markdown')),
                ('publish_dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'MicroBlog',
                'verbose_name_plural': 'MicroBlogs',
                'ordering': ['-publish_dt'],
            },
        ),
    ]
