# Generated by Django 2.1.3 on 2018-12-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microblog',
            name='content',
            field=models.TextField(help_text='markdown'),
        ),
    ]
