# Generated by Django 2.1.3 on 2018-11-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_dt'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('archive', '-update_dt'), 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='blue', help_text='you can use preset color name: blue, geekblue, purple, magenta, red, volcano, gold, lime, green, cyan. or standard RGB, eg: #108ee9, #87d068', max_length=10, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(blank=True, to='topic.Tag'),
        ),
    ]
