# Generated by Django 2.1.3 on 2018-11-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20181125_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#2db7f5', help_text='RGB value, eg: #108ee9, #87d068', max_length=10, verbose_name='color'),
        ),
    ]
