# Generated by Django 2.1.3 on 2018-12-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_auto_20181125_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('archive', '-create_dt'), 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
    ]
