# Generated by Django 2.1.3 on 2018-12-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_auto_20181222_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-topping', 'archive', '-create_dt'), 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AddField(
            model_name='topic',
            name='topping',
            field=models.BooleanField(default=False, help_text='topic not on achive status, topping will sort at first', verbose_name='topping topic'),
        ),
    ]
