# Generated by Django 2.1.3 on 2018-12-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0005_auto_20181222_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('archive', '-pin', '-create_dt'), 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topping',
        ),
        migrations.AddField(
            model_name='topic',
            name='pin',
            field=models.BooleanField(default=False, help_text='push pin topic will sort at first, note: if archived this field will invalid', verbose_name='Pushpin topic'),
        ),
    ]
