# Generated by Django 2.1.7 on 2019-02-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0006_auto_20181222_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
