# Generated by Django 2.1.7 on 2019-03-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0009_auto_20190303_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='pv',
            field=models.IntegerField(default=0, verbose_name='page views'),
        ),
    ]
